modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/MC-U-Team/Attack-Speed-Enchantment/issues"
displayURL="https://u-team.info/mods/attackspeedenchantment"
logoFile="logo.png"
license="Apache-2.0 License"
credits="Team U-Team"
authors="HyCraftHD"

[[mods]]
	modId="attackspeedenchantment"
	version="${file.jarVersion}"
	displayName="Attack Speed Enchantment"
	updateJSONURL="https://api.u-team.info/update/attackspeedenchantment.json"
	description="This mod adds an enchantment that allows you to decrease the attack cooldown. When the enchantment reaches Level 10 the cooldown is removed entirely."
	
	[[dependencies.attackspeedenchantment]]
	    modId="forge"
	    mandatory=true
	    versionRange="[36.1.12,)"
	    ordering="NONE"
	    side="BOTH"
	
	[[dependencies.attackspeedenchantment]]
	    modId="minecraft"
	    mandatory=true
	    versionRange="[1.16.5]"
	    ordering="NONE"
	    side="BOTH"
	    
	[[dependencies.attackspeedenchantment]]
	    modId="uteamcore"
	    mandatory=true
	    versionRange="[3.2.1.195,)"
	    ordering="NONE"
	    side="BOTH"